### ISSUE TITLE
Numbers flickering

### ISSUE THREAD

**Issue by nourserry** [prateekmedia/netspeedsimplified#11]
As the of the latest update, the numbers are flickering and not displaying properly.
I tried to capture a screenshot but it I couldn't, it seemed that whenever I tried it fixed itself for a second.
I uploaded a video [here](https://photos.app.goo.gl/PsnFyV9NPNQYp34w9)

**Comment by prateekmedia** [comment]
Please checkout pull#12 ,

To install that go to that branch and follow the install instructions using make file

**Comment by nourserry** [comment]
Thanks a lot for the quick reply.
I checked the commit and found it's easier for me to just edit the stylesheet.css file, and then re-enable the extension.
It's working perfectly now. ♥

**Comment by prateekmedia** [comment]
Thanks, I have also faced it, if it's not solved even now or you have any queries then just open a new issue or reopen this one.
