### ISSUE TITLE
Arrow icons 

### ISSUE THREAD

**Issue by reginastracii** [prateekmedia/netspeedsimplified#15]
I'm getting squares instead the up and down arrows, sum and the double arrow work fine. 
🡳 and 🡱 don't work for me could be a local issue 

![Screenshot from 2021-04-10 21-24-02](https://user-images.githubusercontent.com/22214293/114283762-55543380-9a43-11eb-9c15-edc109b4a15d.png)

**Comment by prateekmedia** [comment]
> I'm getting squares instead the up and down arrows, sum and the double arrow work fine.
> 🡳 and 🡱 don't work for me could be a local issue
> 
> ![Screenshot from 2021-04-10 21-24-02](https://user-images.githubusercontent.com/22214293/114283762-55543380-9a43-11eb-9c15-edc109b4a15d.png)

It looks like something is wrong with your fonts, you can try changing the arrow icon set in Preferences or you can try to set you own custom font like Monospace, Droid Sans, etc from Preferences.

Either way you will be able to avoid this problem, else please give more info regarding this like shell version and font you have used for the ui.

**Comment by reginastracii** [comment]
I tried switching through the fonts, with no effect. I changed the  🡳 and 🡱 with arrows which do work for me  in the function DIcons(iNum).  gnome 40, fonts various for reference.
