### ISSUE TITLE
Update extension version on the GNOME site

### ISSUE THREAD

**Issue by RedBearAK** [prateekmedia/netspeedsimplified#26]
I like this extension a lot and was able to configure it to be a good replacement for the iStat menus and MenuMeters plugins that I've been using in macOS for many years. Compact vertical stacking, colors, good spacing. Very nice work. 

However, the version that was installed automatically from extensions.gnome.org seemed to have a lot of bugs (like the bad rendering of the character in the tens column, unreliable font coloring, spacing issues, etc.), which all seem to be resolved by downloading the latest version from here manually and running `make install`. 

Please update the version on extensions.gnome.org whenever you can. Thanks!

**Comment by prateekmedia** [comment]
Hi, I have published it for review in Gnome extensions store, if you like the extension then a star to the project will be appreciated.
