### ISSUE TITLE
Gnome 42 support

### ISSUE THREAD

**Issue by siddhpant** [prateekmedia/netspeedsimplified#30]
Was trying to install this but found out no Gnome 42 support is there.

Debian testing has released Gnome 42, so it's a good time to upgrade the extension.

**Comment by chrislea** [comment]
I'd also like to leave a vote for a Gnome 42 version. Thanks so much for writing this extension!

**Comment by prateekmedia** [comment]
Done, expect it soon in the website.

**Comment by siddhpant** [comment]
Thanks!
