### ISSUE TITLE
Showing error after latest update.

### ISSUE THREAD

**Issue by shreedharhegde99** [prateekmedia/netspeedsimplified#34]
When updated to new version, it's showing an error.

![Screenshot 2022-04-10 at 12-29-28 Net speed Simplified - GNOME Shell Extensions](https://user-images.githubusercontent.com/90758718/162606827-f1444fa2-8bb9-4f90-b4de-4e079d44ec01.png)

**Comment by prateekmedia** [comment]
Log out, log in back
