### ISSUE TITLE
While Using VPN, it show double of actual speed

### ISSUE THREAD

**Issue by afzl-wtu** [prateekmedia/netspeedsimplified#35]
I use wireguard vpn on regualar basis. But whenever I turn it on InternetSpeedMonitor shows Double of the actual download upload speed of the connection. 
![image](https://user-images.githubusercontent.com/64379149/169050638-20a52c97-f46f-4393-aecd-8a70511a2f63.png)
Please fix this issue or add an option to select network interface to monitor in settings.

**Comment by afzl-wtu** [comment]
> I second wishing for an option to select the NIC. Thank you for this great extension :)

More deatil here:
https://github.com/rishuinfinity/InternetSpeedMonitor/issues/3

**Comment by Palatis** [comment]
depends on what type of VPN you're using.
1. if the VPN creates a proxy (eg. http, socks) server, no additional traffic is counted. 
2. if the VPN creates a tun/tap interface with custom name, traffic will be counted twice. try direct your VPN software to name the interface according to https://github.com/prateekmedia/netspeedsimplified/blob/e996714914da32074a7836b733ef846101c71089/extension.js#L325-L333.

**Comment by Palatis** [comment]
maybe add an prefs option to allow user input custom filter might also be a good idea?
i'm not familiar with gnome-shell extension development, maybe someday i'll post a PR.

**Comment by mcdemon05** [comment]
Hello.
Cisco AnyConnect makes interface cscotun0
please filter cscotun interfaces

by the way, maybe better add feature that can choose interface for monitoring
