### ISSUE TITLE
Reporting wrong download speed

### ISSUE THREAD

**Issue by Earthling-Z3R0** [prateekmedia/netspeedsimplified#36]
My download speed is being reported as 8.8 M/s while in reality it's 12.5 M/s as shown on my conky and other tools (and which is actually my maximum download speed possible).

Funny thing is when the download is being started it first shows 12.5 M/s for one update interval (set to 1.5 seconds in my case) but then jumps down to 8.8 M/s as the maximum value.

I can't tell right now whether the upload speed is reported correctly or not.

**Comment by prateekmedia** [comment]
Don't set the seconds to 1.5 if you want accurate results, change it to 1
