### ISSUE TITLE
Refresh Time setting causes inaccurate speed if not set to 1.0

### ISSUE THREAD

**Issue by abm6** [prateekmedia/netspeedsimplified#37]
Works fine when refreshTime=1.0

expected bug line [Line: 334] extension.js

**Steps to reproduce:** 

- set refresh time to 1.5 (anything except 1.0)

**Result:** The total net speed or separate upload / download gets altered and shows lesser speed than the actual speed

**Screenshot**

- **Accurate Left Extension** https://github.com/AlShakib/InternetSpeedMeter
- **Inaccurate Right Extension** https://github.com/prateekmedia/netspeedsimplified

![bug](https://user-images.githubusercontent.com/55770187/182623491-93f6d453-a3e4-4d2a-af4a-1b3986c5dadd.jpeg)

**Comment by prateekmedia** [comment]
CPU Load is the two word answer of why it is 1.5 for now

**Comment by abm6** [comment]
Thanks for the explaination. I realize that this is the only way to reduce CPU load.
