### ISSUE TITLE
showing weird speed object instead of the actual speed

### ISSUE THREAD

**Issue by soorajsprakash** [prateekmedia/netspeedsimplified#40]
![image](https://user-images.githubusercontent.com/26853789/192684664-59f3c53b-0d1d-4ead-9a1e-d4971fab0c21.png)

and this refreshes like the speed does 

Using Arch Linux,
Gnome 42.4,
X11.

**Comment by prateekmedia** [comment]
Try SimpleNetSpeed and see if it does the same

**Comment by soorajsprakash** [comment]
No issue with SimpleNetSpeed.

**Comment by jstebenne** [comment]
I'm having the same issue.

Trying SimpleNetSpeed also works without issue

**Comment by prateekmedia** [comment]
Ok I will check, maybe issue with latest gnome 42

**Comment by soorajsprakash** [comment]
possibly, i came to notice this after i got an update (didnt bother to check what were the updates for)

**Comment by miadabdi** [comment]
same for me, on fedora 36 gnome 42.4

**Comment by jstebenne** [comment]
It seems to be fixed for me now, on version 36

**Comment by soorajsprakash** [comment]
yeah fixed. cool 👍🏼
