### ISSUE TITLE
Does not work on Gnome 44-Beta

### ISSUE THREAD

**Issue by aisivan36** [prateekmedia/netspeedsimplified#46]
How to make this work on the latest gnome version? may someone's willing to fix the problem.

**Comment by prateekmedia** [comment]
Tell me what's the error, we don't support 44 currently.

**Comment by danieluhrinyi** [comment]
I experience the same. As I have just upgraded to Fedora 38, which now includes Gnome 44, the extension manager says for this one that "The extension is incompatible with the current GNOME version" and so it is disabled. Thanks for the fix in advance!

**Comment by prateekmedia** [comment]
Published an update on extensions.gnome.org
