### ISSUE TITLE
appIndicator is undefined

### ISSUE THREAD

**Issue by puspamadak** [prateekmedia/netspeedsimplified#47]
The title says it all. Just after installation, it shows this error. The panel just shows --

**Comment by prateekmedia** [comment]
what's your gnome shell version?

**Comment by puspamadak** [comment]
43.4

**Comment by prateekmedia** [comment]
I think this would be fixed after a restart, @puspamadak can you confirm if it's happening now?

**Comment by puspamadak** [comment]
You are right. The problem went out after a logout and login.
