### ISSUE TITLE
add the option use Bits instead of Bytes

### ISSUE THREAD

**Issue by lollilol** [prateekmedia/netspeedsimplified#51]
i have the simple feature request, to add a toggle to turn on displaying the speed in Bits instead of Bytes.
in other words: Mb instead of MB or Mbit/s instead of Mbyte/s

thank you so much for the work so far!

**Comment by mcdemon05** [comment]
You should use method3 - it's bits

**Comment by prateekmedia** [comment]
It is already present, if you click on the net speed widget then it will toggle, as such two of which are in Bits and two are in Bytes.
