### ISSUE TITLE
[New feature] Please add an option to hide the /s part

### ISSUE THREAD

**Issue by benintech** [prateekmedia/netspeedsimplified#57]
To save panel space, you could add an option to not show the `/s` part. It's up to the user to interpret what he sees : for me, something like `3.5m↓  148k↑` is sufficient to know that my current speeds are 3.5 Mbits/s down and 148 Kbit/s up.

Especially useful on a small 13" laptop, where panel space is precious !

**Comment by prateekmedia** [comment]
Already done, See Shorten Units toggle in extension preference.

**Comment by benintech** [comment]
No, I don't think so. "Shorten units" removes the "b" or "B" (e.g., it displays `128k/s` instead of `128kb/s`). But it doesn't remove the `/s` part (e.g., to display `128k`).
